=== Cytior/DicoGame/DicoData/XMLData/xmlittre.dtd
<?xml version="1.0" encoding="utf-8"?>
<!-- XMLittré DTD -->

<!ELEMENT xmlittre (entree+)>
<!ATTLIST xmlittre lettre CDATA #REQUIRED>

<!ELEMENT entree (entete,résumé?,corps,rubrique*)>
<!ATTLIST entree terme CDATA #REQUIRED>
<!ATTLIST entree supplement (0|1) "0">
<!ATTLIST entree sens (1|2|3|4|5|6|7|8|9) "1">

<!-- <!ELEMENT entete ANY> -->
<!ELEMENT entete (#PCDATA|prononciation|nature|indent|cit|a|semantique)*>
<!ELEMENT prononciation (#PCDATA|cit|a|i|span)*>

<!ELEMENT nature (#PCDATA)>

<!ELEMENT corps (variante|rubrique)*>
<!-- <!ELEMENT rubrique (#PCDATA|variante|indent|rubrique)*> -->
<!ELEMENT rubrique ANY>
<!-- pb avec cette liste (REMARQUE|REMARQUES|ÉTYMOLOGIE|SUPPLÉMENT AU DICTIONNAIRE|SYNONYME|HISTORIQUE) à cause des espaces -->
<!ATTLIST rubrique nom CDATA #REQUIRED>
<!ELEMENT indent (#PCDATA|indent|variante|cit|nature|semantique|exemple|a|i|span)*>
<!ELEMENT variante (#PCDATA|indent|cit|nature|semantique|exemple|a|i|span|rubrique)*>
<!ATTLIST variante
	num CDATA #IMPLIED
	option (résumé) #IMPLIED
>
<!ELEMENT résumé (indent|variante)*>

<!ELEMENT cit (#PCDATA|a|i|span)*>
<!ATTLIST cit
	aut CDATA #IMPLIED
	ref CDATA #IMPLIED
	fix CDATA #IMPLIED
	hide (aut|ref|both) #IMPLIED
>

<!ELEMENT a (#PCDATA|nature)*>
<!ATTLIST a ref CDATA #REQUIRED>

<!ELEMENT i (#PCDATA)*>
<!ATTLIST i class (botanique) #IMPLIED>
<!ATTLIST i lang (ar|de|en|es|fr|it|la|sa|syc) #IMPLIED>

<!ELEMENT span (#PCDATA|a|i)*>
<!ATTLIST span lang (ar|de|en|es|fr|it|la|sa|syc) #IMPLIED>

<!ELEMENT exemple (#PCDATA|a)*>

<!ELEMENT semantique (#PCDATA)>
<!ATTLIST semantique type (indicateur|domaine) #IMPLIED>

=== Cytior/DicoGame/DicoData/XMLData/y.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xmlittre SYSTEM "xmlittre.dtd">
<!--
XMLittré, réalisé par François Gannaz <francois.gannaz@free.fr>.

Le contenu de ce document est sous licence "Creative Commons Paternité - Partage des conditions initiales
à l'identique 3.0", alias CC-BY-SA 3.0.
Pour obtenir copie de cette licence, consulter http://creativecommons.org/licenses/by-sa/3.0/deed.fr
ou envoyer un courrier à Creative Commons, 171 2nd Street, Suite 300, San Francisco, California, 94105, USA.

La suppression des éléments de balisage XML permet d'obtenir un texte
placé dans le domaine public. Voir le script "xml2txt.pl" à ce sujet.

The content of this document is licensed under the CC-BY-SA license
See http://creativecommons.org/licenses/by-sa/3.0
-->
<xmlittre lettre="Y">
<entree terme="Y" sens="1">
<entete>
	<prononciation>i-grèk, et, selon l'épellation moderne, i</prononciation>
	<nature>s. m.</nature>
</entete>
<corps>
<variante num="1">Vingt-quatrième lettre de l'alphabet. 
<cit aut="LA MOTHE LE VAYER" ref="la Promenade, Dial. I">L'i final était trop simple et mal propre à recevoir l'ornement des paraphes ou bravoures dont la queue de l'y grec est susceptible</cit>
</variante>
<variante num="2">Dans les lettres numérales employées au moyen âge, Y valait 150 ; surmonté d'un trait, il valait 150 000.
</variante>
<variante num="3">Sert souvent en algèbre à désigner une inconnue.
</variante>
<variante num="4">Est un signe qui se met (rarement aujourd'hui) à Paris sur les boutiques, pour indiquer qu'on vend à prix fixe.
</variante>
<variante num="5">Sur les anciennes monnaies de France, marque celles qui ont été frappées à Bourges.
</variante>
<variante num="6">Poinçon d'acier au bout duquel est empreint un Y, pour frapper ou imprimer cette lettre.
</variante>
<variante num="7">Outil des glaciers.
</variante>
<variante num="8">Espèce de papillon.
</variante>
<variante num="9">Embranchement en forme d'y. 
<cit aut="SAUSSURE" ref="Voy. Alpes, t. v, p. 222">Cette grande chaîne qui, en s'abaissant graduellement, vient aboutir à la Méditerranée, se divise là comme un y grec en deux branches inégales</cit>
<cit aut="TH. GAUTIER" ref="le Bien public, 10 mars 1872">Placés à l'y du carrefour, nous hésitions entre les deux routes</cit>
</variante>
</corps>
<rubrique nom="REMARQUE">
<indent>1. Dans les transcriptions de mots grecs <i>y</i> répond à l'υ grec, que les Grecs modernes prononcent <i>i</i>. On le conserve aussi dans quelques mots empruntés des langues étrangères.
</indent>
<indent>2. Y a deux prononciations : tantôt il représente le son simple d'un <i>i</i>, comme dans physique, hypocrisie, etc., tantôt le son de deux <i>i</i> comme dans appuyer (appui-ié). Quand il est précédé d'un <i>a</i>, il donne à cet <i>a</i> le son d'un <i>è</i>, et garde celui d'<i>i</i> : pays, payer, etc. Quand il est précédé d'un <i>e</i>, il donne à cet <i>e</i> le son <i>è</i> : grasseyer. Quand il est précédé d'un <i>o</i>, la prononciation n'est pas fixée : les uns, et l'Académie est de ce nombre, donnent à cet <i>o</i> le son de <i>oi</i> et à <i>y</i> le son de l'<i>i</i> : si-toi-iin, roi-ial, em-ploi-ié, etc. ; les autres laissent à l'<i>o</i> le son qui lui est propre : si-to-iin, ro-ial, em-plo-ié ; c'est la prononciation ancienne, celle que l'Académie elle-même recommandait en 1694, celle qui doit être préférée.
</indent>
<indent>3. Dans certains mots l'<i>y</i> initial ne reçoit pas l'élision de l'article : le yatagan.
</indent>
<indent>4. Voici une règle empirique, qui peut être d'une grande utilité pour savoir quand il faut un <i>y</i> ou un <i>i</i> dans certains mots tirés du grec. Une foule de gens écrivent Hyppolite, Hyppocrate. Toutes les fois qu'il y a deux <i>p</i> à <i>hip</i>, il ne faut pas d'<i>y</i> grec ; au contraire, il en faut un quand il n'y a qu'un <i>p</i> : Hippolyte, Hippocrate, Hippias, et hypothèse, hyperbole, hypothèque.
</indent>
</rubrique>
<rubrique nom="HISTORIQUE">
<indent>XIVe s. 
<cit aut="DE LABORDE" ref="Émaux, p. 546">Un petit fermail d'or, a un Y gregeois ou milieu, et autour a x perles</cit>
</indent>
</rubrique>
<rubrique nom="ÉTYMOLOGIE">
<indent>Lat. <i lang="la">y</i>, répondant à l'υ grec.
</indent>
</rubrique>
</entree>

<entree terme="Y" sens="2">
<entete>
	<prononciation>i</prononciation>
<indent>Ce mot est l'objet de la même discussion que <i>en</i>. Le Dict. de l'Académie le nomme adverbe relatif ; M. Jullien y voit un nom de lieu qui, rationnellement, est le cas attributif du nom abstrait <i>ce, ceci, cela</i>. Le fait est que y, représentant le latin ibi, est, d'abord et étymologiquement, un adverbe de lieu, ou, si l'on veut, plus exactement, un nom de lieu pris adverbialement. Après cette signification primitive, y, par extension, est employé à exprimer toute sorte de rapports.
</indent>
</entete>
<corps>
<variante num="1">En cet endroit-là. Voulez-vous y aller? Rendez-vous-y. J'y cours. 
<cit aut="SÉV." ref="22 nov. 1671">La Provence est mon pays depuis que vous y êtes</cit>
<cit aut="BOILEAU" ref="Héros de romans.">De son temps [un conquérant], les hommes venaient ici [dans les enfers] tous les jours par trente et quarante mille ; jamais personne n'y en a tant envoyé</cit>
<cit aut="RAC." ref="Mithr. I, 3">Ici! vous y pourriez rencontrer votre perte</cit>
<cit aut="RAC." ref="Lettres à son fils, 2 mai 1698">Il y aura demain trois semaines que je ne suis sorti de Paris ; et je pourrais bien y en demeurer encore autant</cit>
<cit aut="VOLT." ref="Charles XII, 4">On ne recevait plus de nouvelles de la Suède, et on ne pouvait y en faire tenir</cit>
<cit aut="ID." ref="Lett. Damilaville, 17 déc. 1766">J'ai empêché, autant que je l'ai pu, que le petit Avis entrât en France ; mais plusieurs voyageurs y en ont apporté des exemplaires</cit>
<cit aut="BARTHÉL." ref="Anach. ch. 28">Eh non, reprit un autre, il [Diogène] est de Sinope ; les habitants l'ont condamné à sortir de leur ville. - Et moi je les ai condamnés à y rester</cit>
<indent>Y avec s'en retourner, s'en aller, s'en venir. 
<cit aut="GUI PATIN" ref="Lettres, t. II, p. 497">J'ai ici un honnête homme de Lyon, qui s'y en retournera après Pâques</cit>
<cit aut="MOL." ref="D. Juan, IV, 11">D. Juan : Je veux souper en repos, au moins, et qu'on ne laisse entrer personne. - Sganarelle : Laissez-moi faire, je m'y en vais moi-même</cit>
</indent>
</variante>
<variante num="2">Du sens d'adverbe de lieu, y passe au rôle de pronom (comme où qui, du rôle d'adverbe de lieu, passe au rôle de pronom relatif dans : le bonheur où j'aspire), et signifie en ce, en ceci, en cela, en cette chose, en ces choses. 
<cit aut="DESC." ref="Méth. II, 2">Pour toutes les opinions que j'avais reçues jusques alors en ma créance, je ne pouvais mieux faire que d'entreprendre une bonne fois de les en ôter, afin d'y en remettre par après ou d'autres meilleures ou bien les mêmes...</cit>
<cit aut="CORN" ref="Cinna, Examen.">Rien n'y contredit [dans cette tragédie] l'histoire</cit>
<cit aut="MOL." ref="Ec. des f. IV, 8">Et, pour se bien conduire en ces difficultés, Il y faut, comme en tout, fuir les extrémités</cit>
<cit aut="BOSSUET" ref="Hist. II, 13">Écritures.... qu'on a conservées avec tant de religion, qu'on n'a pas cru pouvoir sans impiété y altérer une seule lettre</cit>
<cit aut="ID." ref="Méd. sur l'Év. 2e partie, 7e jour.">En même temps que pour prier on se met dans l'esprit cette première vérité.... on doit encore s'y en mettre une autre....</cit>
<cit aut="RAC." ref="Mithr. III, 5">Mon trône vous est dû : loin de m'en repentir, Je vous y place même avant que de partir</cit>
<cit aut="VOLT." ref="Dict. phil. Pierre le Grand.">Une mouche, ayant vu un jour une hirondelle, qui, en volant, emportait des toiles d'araignée, en voulut faire autant, elle y fut prise</cit>
<indent>Il se dit dans le même sens avec un nom de personne. 
<cit aut="MOL." ref="Amph. II, 6">Je ne distingue rien en celui qui m'offense ; Tout y devient l'objet de mon courroux</cit>
<cit aut="BOSSUET" ref="Libre arb. IV">Et encore que ces sentiments n'aient pas été assez vifs, ni assez suivis dans les païens, nous y en voyons des vestiges qui...</cit>
<cit aut="LA BRUY." ref="VIII">L'on me dit tant de mal de cet homme, et j'y en vois si peu, que je commence à soupçonner qu'il n'ait un mérite importun, et qui éteigne celui des autres</cit>
</indent>
</variante>
<variante num="3">Il se dit aussi pour : à ce, à ceci, à cette chose, à ces choses. 
<cit aut="CORN." ref="Hor. I, 3">Dure à jamais le mal, s'il y faut ce remède!</cit>
<cit aut="ID." ref="Poly. IV, 6">Ici l'honneur m'oblige, et j'y veux satisfaire</cit>
<cit aut="MOL." ref="Am. méd. II, 3">Il faut toujours garder les formalités, quoi qu'il puisse arriver. - Pour moi, j'y suis sévère en diable</cit>
<cit aut="ID." ref="Mis. v, 3">Je me vois, ma cousine, ici persécutée Par des gens dont l'humeur y paraît concertée</cit>
<cit aut="ID." ref="G. Dand. I, 7">Par ma foi, il mériterait qu'elle lui fît dire vrai ; et, si j'étais en sa place, je n'y marchanderais pas</cit>
<cit aut="ID." ref="ib. II, 10">Promettez-moi donc.... que je pourrai vous parler cette nuit. - J'y ferai mes efforts</cit>
<cit aut="ID." ref="Tart. III, 6">Accablez-moi de noms encor plus détestés : Je n'y contredis point, je les ai mérités</cit>
<cit aut="SÉV." ref="26 avril 1680">Le roi donne cent mille francs à Brancas pour marier sa fille au duc de Brancas son neveu ; et Brancas y ajoute cent mille écus</cit>
<cit aut="ID." ref="19 août 1675">Aussitôt qu'il sera temps d'agir, je n'y perdrai pas un seul moment</cit>
<cit aut="BOSSUET" ref="Louis de Bourbon.">Sensible jusques à la fin à la tendresse des siens, il ne s'y laissa jamais vaincre ; et au contraire il craignait toujours de trop donner à la nature</cit>
<cit aut="QUIN." ref="Armide, v, 1">Aimons-nous, tout nous y convie</cit>
